package com.ktw.duan.dao;

import com.ktw.duan.po.GitPo;

public interface GitPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Sun Oct 21 12:57:47 GMT+08:00 2018
     */
    int insert(GitPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Sun Oct 21 12:57:47 GMT+08:00 2018
     */
    int insertSelective(GitPo record);
}